In [1]:
# %run -m pip install numpy==1.26.4
# %run -m pip install gmsh
# %run -m pip install polars

In [2]:
import numpy as np
import gmsh
import os, sys, shutil, glob
import polars as pl

In [3]:
# Размер пластины по оси Х, м
A = 1.0
# Размер пластины по оси У, м 
B = 1.0
# Толщины слоев, м
H = np.array([0.001,0.001,0.001])
# Число слоев
N = H.shape[0]
# Число Элементов Сетки по осям X:Nx, Y:Ny и Z:Nz
Nx = 128
Ny = 128
Nz = 1


In [4]:
Curr_Path = os.getcwd()
print(Curr_Path)
Results_Path = os.path.join(Curr_Path,'Results')
print( Results_Path)
os.makedirs(Results_Path,mode=0o777, exist_ok=True)

FName0 = f"Model_1_GMSH_OCC_A_{A}_B_{B}_N_{N}_Nx_{Nx}_Ny_{Ny}_Nz_{Nz}"
FPath = os.path.join(Results_Path,f"Model_1_GMSH_OCC_A_{A}_B_{B}_N_{N}_Nx_{Nx}_Ny_{Ny}_Nz_{Nz}")
os.makedirs(FPath,mode=0o777, exist_ok=True)

/Users/collapsor/PycharmProjects/Taichi_project
/Users/collapsor/PycharmProjects/Taichi_project/Results


In [5]:
gmsh.initialize()

In [6]:
gmsh.model.add("Model_1_gmsh_occ")

In [7]:
ElSize = np.min([A/Nx,B/Ny])
ElSize

np.float64(0.0078125)

In [8]:
gmsh.model.occ.addRectangle(x=0,y=0,z=0,dx=A,dy=B,tag=1)

1

In [9]:
gmsh.model.occ.synchronize()

In [10]:
Surfaces = gmsh.model.occ.getEntities(dim=2)
Surfaces

[(2, 1)]

In [11]:
Layer_mesh = gmsh.model.occ.extrude(dimTags=[(2, 1)], 
                                    dx=0, dy=0, dz=H[0], 
                                    numElements=[1], 
                                    heights=[1],
                                    recombine=True)

In [12]:
gmsh.model.occ.synchronize()
gmsh.fltk.run()

-------------------------------------------------------
Version       : 4.13.1
License       : GNU General Public License
Build OS      : MacOSARM-sdk
Build date    : 20240524
Build host    : gmsh.info
Build options : 64Bit ALGLIB[contrib] ANN[contrib] Bamg Blas[petsc] Blossom Cgns DIntegration Dlopen DomHex Eigen[contrib] Fltk GMP Gmm[contrib] Hxt Jpeg Kbipack Lapack[petsc] MathEx[contrib] Med Mesh Metis[contrib] Mpeg Netgen Nii2mesh ONELAB ONELABMetamodel OpenCASCADE OpenCASCADE-CAF OpenGL OpenMP OptHom PETSc Parser Plugins Png Post QuadMeshingTools QuadTri Solver TetGen/BR TinyXML2[contrib] TouchBar Untangle Voro++[contrib] WinslowUntangler Zlib
FLTK version  : 1.4.0
PETSc version : 3.17.4 (real arithmtic)
OCC version   : 7.7.2
MED version   : 4.1.0
Packaged by   : geuzaine
Web site      : https://gmsh.info
Issue tracker : https://gitlab.onelab.info/gmsh/gmsh/issues
-------------------------------------------------------


2025-03-10 19:34:39.412 python[83017:13189431] +[IMKClient subclass]: chose IMKClient_Modern
2025-03-10 19:34:39.412 python[83017:13189431] +[IMKInputSession subclass]: chose IMKInputSession_Modern


In [13]:
Points = gmsh.model.occ.getEntities(dim=0)
Points

[(0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8)]

In [14]:
Layer_mesh #[0][0]

[(2, 6), (3, 1), (2, 2), (2, 3), (2, 4), (2, 5)]

In [15]:
#gmsh.model.mesh.setSize([(Layer_mesh[0][0], Layer_mesh[0][1])], ElSize)

In [16]:
for i in range(1,N):
    #print(f"Layer_{i+1}")
    Layer_mesh = gmsh.model.occ.extrude(dimTags=[Layer_mesh[0]], 
                                        dx=0, dy=0, dz=H[i], 
                                        numElements=[1], 
                                        heights=[1], 
                                        recombine=True)
    gmsh.model.occ.synchronize()
    #gmsh.model.mesh.setSize([(Layer_mesh[0][0], Layer_mesh[0][1])], ElSize)

gmsh.model.occ.synchronize()
gmsh.fltk.run()

-------------------------------------------------------
Version       : 4.13.1
License       : GNU General Public License
Build OS      : MacOSARM-sdk
Build date    : 20240524
Build host    : gmsh.info
Build options : 64Bit ALGLIB[contrib] ANN[contrib] Bamg Blas[petsc] Blossom Cgns DIntegration Dlopen DomHex Eigen[contrib] Fltk GMP Gmm[contrib] Hxt Jpeg Kbipack Lapack[petsc] MathEx[contrib] Med Mesh Metis[contrib] Mpeg Netgen Nii2mesh ONELAB ONELABMetamodel OpenCASCADE OpenCASCADE-CAF OpenGL OpenMP OptHom PETSc Parser Plugins Png Post QuadMeshingTools QuadTri Solver TetGen/BR TinyXML2[contrib] TouchBar Untangle Voro++[contrib] WinslowUntangler Zlib
FLTK version  : 1.4.0
PETSc version : 3.17.4 (real arithmtic)
OCC version   : 7.7.2
MED version   : 4.1.0
Packaged by   : geuzaine
Web site      : https://gmsh.info
Issue tracker : https://gitlab.onelab.info/gmsh/gmsh/issues
-------------------------------------------------------


In [17]:
Points = gmsh.model.occ.getEntities(dim=0)
Points

[(0, 1),
 (0, 2),
 (0, 3),
 (0, 4),
 (0, 5),
 (0, 6),
 (0, 7),
 (0, 8),
 (0, 9),
 (0, 10),
 (0, 11),
 (0, 12),
 (0, 13),
 (0, 14),
 (0, 15),
 (0, 16)]

In [18]:
# import random
# 
# for point in Points:
#     # print(point)
#     length = ElSize * random.uniform(0.8, 1.2)
#     # print(length)
#     gmsh.model.mesh.setSize([(0, point[1])], length)

Points = gmsh.model.occ.getEntities(dim=0)
for point in Points:
    # 这里可以根据点的坐标或其它规则，设置不同的尺寸
    # 假设根据 x 坐标来设置尺寸
    x, y, z = gmsh.model.occ.getCenterOfMass(point[0], point[1])
    size = 0.001 + 0.002 * abs(x - A/2)  # 例如在 x=A/2 附近更细
    gmsh.model.mesh.setSize([point], size)

In [19]:
gmsh.model.mesh.setSize(Points, ElSize)

In [20]:
gmsh.model.mesh.setTransfiniteAutomatic(recombine=True)
gmsh.option.setNumber("Mesh.Algorithm", 1)
gmsh.option.setNumber("Mesh.Algorithm3D", 1)
gmsh.option.setNumber("Mesh.OptimizeNetgen", 1)
gmsh.model.mesh.generate(3)

Info    : Meshing 1D...
Info    : [  0%] Meshing curve 1 (Line)
Info    : [ 10%] Meshing curve 2 (Line)
Info    : [ 10%] Meshing curve 3 (Line)
Info    : [ 20%] Meshing curve 4 (Line)
Info    : [ 20%] Meshing curve 5 (Extruded)
Info    : [ 20%] Meshing curve 6 (Extruded)
Info    : [ 30%] Meshing curve 7 (Extruded)
Info    : [ 30%] Meshing curve 8 (Extruded)
Info    : [ 30%] Meshing curve 9 (Extruded)
Info    : [ 40%] Meshing curve 10 (Extruded)
Info    : [ 40%] Meshing curve 11 (Extruded)
Info    : [ 40%] Meshing curve 12 (Extruded)
Info    : [ 50%] Meshing curve 13 (Extruded)
Info    : [ 50%] Meshing curve 14 (Extruded)
Info    : [ 60%] Meshing curve 15 (Extruded)
Info    : [ 60%] Meshing curve 16 (Extruded)
Info    : [ 60%] Meshing curve 17 (Extruded)
Info    : [ 70%] Meshing curve 18 (Extruded)
Info    : [ 70%] Meshing curve 19 (Extruded)
Info    : [ 70%] Meshing curve 20 (Extruded)
Info    : [ 80%] Meshing curve 21 (Extruded)
Info    : [ 80%] Meshing curve 22 (Extruded)
Info    : [

In [21]:
gmsh.model.occ.synchronize()
gmsh.fltk.run()

-------------------------------------------------------
Version       : 4.13.1
License       : GNU General Public License
Build OS      : MacOSARM-sdk
Build date    : 20240524
Build host    : gmsh.info
Build options : 64Bit ALGLIB[contrib] ANN[contrib] Bamg Blas[petsc] Blossom Cgns DIntegration Dlopen DomHex Eigen[contrib] Fltk GMP Gmm[contrib] Hxt Jpeg Kbipack Lapack[petsc] MathEx[contrib] Med Mesh Metis[contrib] Mpeg Netgen Nii2mesh ONELAB ONELABMetamodel OpenCASCADE OpenCASCADE-CAF OpenGL OpenMP OptHom PETSc Parser Plugins Png Post QuadMeshingTools QuadTri Solver TetGen/BR TinyXML2[contrib] TouchBar Untangle Voro++[contrib] WinslowUntangler Zlib
FLTK version  : 1.4.0
PETSc version : 3.17.4 (real arithmtic)
OCC version   : 7.7.2
MED version   : 4.1.0
Packaged by   : geuzaine
Web site      : https://gmsh.info
Issue tracker : https://gitlab.onelab.info/gmsh/gmsh/issues
-------------------------------------------------------


In [22]:
gmsh.model.mesh.createEdges()
gmsh.model.mesh.createFaces()

In [23]:
nodeTags, nodeCoords, _ = gmsh.model.mesh.getNodes(dim=3,includeBoundary=True)

In [24]:
gmsh.model.occ.synchronize()
gmsh.fltk.run()

-------------------------------------------------------
Version       : 4.13.1
License       : GNU General Public License
Build OS      : MacOSARM-sdk
Build date    : 20240524
Build host    : gmsh.info
Build options : 64Bit ALGLIB[contrib] ANN[contrib] Bamg Blas[petsc] Blossom Cgns DIntegration Dlopen DomHex Eigen[contrib] Fltk GMP Gmm[contrib] Hxt Jpeg Kbipack Lapack[petsc] MathEx[contrib] Med Mesh Metis[contrib] Mpeg Netgen Nii2mesh ONELAB ONELABMetamodel OpenCASCADE OpenCASCADE-CAF OpenGL OpenMP OptHom PETSc Parser Plugins Png Post QuadMeshingTools QuadTri Solver TetGen/BR TinyXML2[contrib] TouchBar Untangle Voro++[contrib] WinslowUntangler Zlib
FLTK version  : 1.4.0
PETSc version : 3.17.4 (real arithmtic)
OCC version   : 7.7.2
MED version   : 4.1.0
Packaged by   : geuzaine
Web site      : https://gmsh.info
Issue tracker : https://gitlab.onelab.info/gmsh/gmsh/issues
-------------------------------------------------------


In [25]:
nodeTags.max()

np.uint64(67600)

In [26]:
nodeTags.shape

(101400,)

In [27]:
nodeTags

array([2065, 2066, 2067, ...,   14,   15,   16], dtype=uint64)

In [28]:
nodeCoords.shape

(304200,)

In [29]:
nodeCoords

array([0.00775194, 0.00775194, 0.        , ..., 0.        , 1.        ,
       0.003     ])

In [30]:
nodeCoords.shape[0]/3

101400.0

In [31]:
nodeCoords.resize((nodeCoords.shape[0]//3,3))
nodeCoords

array([[0.00775194, 0.00775194, 0.        ],
       [0.00775194, 0.01550388, 0.        ],
       [0.00775194, 0.02325581, 0.        ],
       ...,
       [1.        , 0.        , 0.003     ],
       [1.        , 1.        , 0.003     ],
       [0.        , 1.        , 0.003     ]])

In [32]:
NodesData = np.hstack((nodeTags[:,np.newaxis],nodeCoords))

In [33]:
NodesData

array([[2.06500000e+03, 7.75193798e-03, 7.75193798e-03, 0.00000000e+00],
       [2.06600000e+03, 7.75193798e-03, 1.55038760e-02, 0.00000000e+00],
       [2.06700000e+03, 7.75193798e-03, 2.32558140e-02, 0.00000000e+00],
       ...,
       [1.40000000e+01, 1.00000000e+00, 0.00000000e+00, 3.00000000e-03],
       [1.50000000e+01, 1.00000000e+00, 1.00000000e+00, 3.00000000e-03],
       [1.60000000e+01, 0.00000000e+00, 1.00000000e+00, 3.00000000e-03]])

In [34]:
gmsh.option.setNumber("Mesh.SaveAll", 1)
gmsh.option.setNumber("Mesh.SaveGroupsOfNodes", 1)

gmsh.option.setNumber("Mesh.Format", 1)
gmsh.write(os.path.join(FPath,FName0+".msh"))

gmsh.option.setNumber("Mesh.Format", 27)
gmsh.write(os.path.join(FPath,FName0+".stl"))

Info    : Writing '/Users/collapsor/PycharmProjects/Taichi_project/Results/Model_1_GMSH_OCC_A_1.0_B_1.0_N_3_Nx_128_Ny_128_Nz_1/Model_1_GMSH_OCC_A_1.0_B_1.0_N_3_Nx_128_Ny_128_Nz_1.msh'...
Info    : Done writing '/Users/collapsor/PycharmProjects/Taichi_project/Results/Model_1_GMSH_OCC_A_1.0_B_1.0_N_3_Nx_128_Ny_128_Nz_1/Model_1_GMSH_OCC_A_1.0_B_1.0_N_3_Nx_128_Ny_128_Nz_1.msh'
Info    : Writing '/Users/collapsor/PycharmProjects/Taichi_project/Results/Model_1_GMSH_OCC_A_1.0_B_1.0_N_3_Nx_128_Ny_128_Nz_1/Model_1_GMSH_OCC_A_1.0_B_1.0_N_3_Nx_128_Ny_128_Nz_1.stl'...
Info    : Done writing '/Users/collapsor/PycharmProjects/Taichi_project/Results/Model_1_GMSH_OCC_A_1.0_B_1.0_N_3_Nx_128_Ny_128_Nz_1/Model_1_GMSH_OCC_A_1.0_B_1.0_N_3_Nx_128_Ny_128_Nz_1.stl'


In [35]:
NodesData_pl = pl.dataframe.DataFrame(NodesData,schema=[('Node',int),('X',float),('Y',float),('Z',float)])

In [36]:
NodesData_pl

shape: (101_400, 4)
┌──────┬──────────┬──────────┬───────┐
│ Node ┆ X        ┆ Y        ┆ Z     │
│ ---  ┆ ---      ┆ ---      ┆ ---   │
│ i64  ┆ f64      ┆ f64      ┆ f64   │
╞══════╪══════════╪══════════╪═══════╡
│ 2065 ┆ 0.007752 ┆ 0.007752 ┆ 0.0   │
│ 2066 ┆ 0.007752 ┆ 0.015504 ┆ 0.0   │
│ 2067 ┆ 0.007752 ┆ 0.023256 ┆ 0.0   │
│ 2068 ┆ 0.007752 ┆ 0.031008 ┆ 0.0   │
│ 2069 ┆ 0.007752 ┆ 0.03876  ┆ 0.0   │
│ …    ┆ …        ┆ …        ┆ …     │
│ 12   ┆ 0.0      ┆ 1.0      ┆ 0.002 │
│ 13   ┆ 0.0      ┆ 0.0      ┆ 0.003 │
│ 14   ┆ 1.0      ┆ 0.0      ┆ 0.003 │
│ 15   ┆ 1.0      ┆ 1.0      ┆ 0.003 │
│ 16   ┆ 0.0      ┆ 1.0      ┆ 0.003 │
└──────┴──────────┴──────────┴───────┘

In [37]:
NodesData_pl.shape,type(NodesData_pl)

((101400, 4), polars.dataframe.frame.DataFrame)

In [38]:
NodesData_pl[0]["X"][0]


0.007751937984496138

In [39]:
NodesData_pl["X"][0]

0.007751937984496138

In [40]:
node_data = NodesData_pl.to_numpy()
node_data

array([[2.06500000e+03, 7.75193798e-03, 7.75193798e-03, 0.00000000e+00],
       [2.06600000e+03, 7.75193798e-03, 1.55038760e-02, 0.00000000e+00],
       [2.06700000e+03, 7.75193798e-03, 2.32558140e-02, 0.00000000e+00],
       ...,
       [1.40000000e+01, 1.00000000e+00, 0.00000000e+00, 3.00000000e-03],
       [1.50000000e+01, 1.00000000e+00, 1.00000000e+00, 3.00000000e-03],
       [1.60000000e+01, 0.00000000e+00, 1.00000000e+00, 3.00000000e-03]])

In [41]:
node_data=np.unique(node_data, axis=0)
node_data

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.00000000e+00, 1.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       ...,
       [6.75980000e+04, 9.92248062e-01, 9.76744186e-01, 3.00000000e-03],
       [6.75990000e+04, 9.92248062e-01, 9.84496124e-01, 3.00000000e-03],
       [6.76000000e+04, 9.92248062e-01, 9.92248062e-01, 3.00000000e-03]])

In [42]:
node_data[node_data.shape[0]-1]

array([6.76000000e+04, 9.92248062e-01, 9.92248062e-01, 3.00000000e-03])

In [43]:
node_data.shape

(67600, 4)

In [44]:
import math
math.sqrt(node_data.shape[0] // 4)

130.0

In [45]:
import taichi as ti
ti.init(arch=ti.gpu ,kernel_profiler = True)

[Taichi] version 1.7.2, llvm 15.0.7, commit 0131dce9, osx, python 3.9.6


[I 03/10/25 19:34:47.342 13189431] [shell.py:_shell_pop_print@23] Graphical python shell detected, using wrapped sys.stdout


[Taichi] Starting on arch=metal


In [46]:
nodes = node_data[:, 0].astype(int)
coordinates = node_data[:, 1:]

In [47]:
nodes

array([    1,     2,     3, ..., 67598, 67599, 67600])

In [48]:
coordinates

array([[0.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 1.        , 0.        ],
       ...,
       [0.99224806, 0.97674419, 0.003     ],
       [0.99224806, 0.98449612, 0.003     ],
       [0.99224806, 0.99224806, 0.003     ]])

In [49]:
coordinates[:10]

array([[0.   , 0.   , 0.   ],
       [1.   , 0.   , 0.   ],
       [1.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 0.   , 0.001],
       [1.   , 0.   , 0.001],
       [1.   , 1.   , 0.001],
       [0.   , 1.   , 0.001],
       [0.   , 0.   , 0.002],
       [1.   , 0.   , 0.002]])

In [50]:
nodes.shape

(67600,)

In [51]:
num_nodes = nodes.shape[0]
X = ti.field(dtype=ti.f32, shape=num_nodes)
Y = ti.field(dtype=ti.f32, shape=num_nodes)
Z = ti.field(dtype=ti.f32, shape=num_nodes)

In [52]:
for i in range(num_nodes):
    X[i] = coordinates[i, 0]
    Y[i] = coordinates[i, 1]
    Z[i] = coordinates[i, 2] 

In [53]:
X[1],Y[1],Z[1]

(1.0, 0.0, 0.0)

In [54]:
layer = 4

In [55]:
import math
n = math.sqrt(node_data.shape[0] // layer)
n

130.0

In [56]:
n= int(n)
n

130

In [57]:
@ti.func
def get_index(i,j,k):
    return k * n * n + j * n + i

In [58]:
quad_size = 1.0 / n
dt = 4e-2 / n
substeps = int(1 / 60 // dt)  

gravity = ti.Vector([0, -9.8, 0])
spring_Y = 3e4
dashpot_damping = 1e4
drag_damping = 1

ball_radius = 0.3
ball_center = ti.Vector.field(3, dtype=float, shape=(1, ))
ball_center[0] = [0, 0, 0]

In [59]:
x = ti.Vector.field(3, dtype=float, shape= (n,n,layer))
v = ti.Vector.field(3, dtype=float, shape= (n,n,layer))

In [60]:
h = H[0]
h

np.float64(0.001)

In [61]:
@ti.func
def rearrange(x):
    return x * (1 + ti.sin(x))
    # return ti.sin(x) + x

In [62]:
@ti.kernel
def initialize_mass_points():
    for idx in range(num_nodes):
        node_x, node_y, node_z = X[idx], Y[idx], Z[idx]

        k = int(ti.round(node_z / h))  
        j = int(node_y // (1.0 / n))
        i = int(node_x // (1.0 / n))

        k = min(max(k, 0), layer-1)
        j = min(max(j, 0), n - 1)
        i = min(max(i, 0), n - 1)

        x[i, j, k] = ti.Vector([
            rearrange(node_x - 0.5) -0.2,
            node_z * 3 + 0.6,
            rearrange(node_y - 0.5) -0.2
        ]) 
        v[i, j, k] = ti.Vector([0.0, 0.0, 0.0])

In [63]:
initialize_mass_points()

In [64]:
x_numpy = x.to_numpy()
print("size:",x_numpy[0].shape)
print(x_numpy[0])

size: (130, 4, 3)
[[[-0.4602872   0.6        -0.4602872 ]
  [-0.4602872   0.60300004 -0.4602872 ]
  [-0.4602872   0.606      -0.4602872 ]
  [-0.4602872   0.609      -0.4602872 ]]

 [[-0.4602872   0.6        -0.4596076 ]
  [-0.4602872   0.60300004 -0.4596076 ]
  [-0.4602872   0.606      -0.4596076 ]
  [-0.4602872   0.609      -0.4596076 ]]

 [[-0.4602872   0.6        -0.458836  ]
  [-0.4602872   0.60300004 -0.458836  ]
  [-0.4602872   0.606      -0.458836  ]
  [-0.4602872   0.609      -0.458836  ]]

 ...

 [[-0.4602872   0.6         0.5101562 ]
  [-0.4602872   0.60300004  0.5101562 ]
  [-0.4602872   0.606       0.5101562 ]
  [-0.4602872   0.609       0.5101562 ]]

 [[-0.4602872   0.6         0.5248885 ]
  [-0.4602872   0.60300004  0.5248885 ]
  [-0.4602872   0.606       0.5248885 ]
  [-0.4602872   0.609       0.5248885 ]]

 [[-0.4602872   0.6         0.5397128 ]
  [-0.4602872   0.60300004  0.5397128 ]
  [-0.4602872   0.606       0.5397128 ]
  [-0.4602872   0.609       0.5397128 ]]]


In [65]:
x_numpy[0][129]

array([[-0.4602872 ,  0.6       ,  0.5397128 ],
       [-0.4602872 ,  0.60300004,  0.5397128 ],
       [-0.4602872 ,  0.606     ,  0.5397128 ],
       [-0.4602872 ,  0.609     ,  0.5397128 ]], dtype=float32)

In [66]:
num_triangles = (n - 1) * (n - 1) * 2 * layer
indices = ti.field(int, shape=num_triangles * 3)
vertices = ti.Vector.field(3, dtype=float, shape=n * n * layer)
colors = ti.Vector.field(3, dtype=float, shape=n * n * layer)

In [67]:
@ti.kernel
def initialize_mesh_indices():
    for i, j, k in ti.ndrange(n - 1, n - 1, layer):
        quad_id = (k * (n - 1) * (n - 1)) + (i * (n - 1)) + j 
        
        base_index = k * n * n  
        
        indices[quad_id * 6 + 0] = base_index + i * n + j
        indices[quad_id * 6 + 1] = base_index + (i + 1) * n + j
        indices[quad_id * 6 + 2] = base_index + i * n + (j + 1)
        
  
        indices[quad_id * 6 + 3] = base_index + (i + 1) * n + j + 1
        indices[quad_id * 6 + 4] = base_index + i * n + (j + 1)
        indices[quad_id * 6 + 5] = base_index + (i + 1) * n + j

    for i, j, k in ti.ndrange(n, n, layer):
        idx = k * n * n + i * n + j
        if (i // 4 + j // 4 + k) % 2 == 0: 
            colors[idx] = (0.22, 0.72, 0.52)  
        else:
            colors[idx] = (1, 0.334, 0.52)

In [68]:
initialize_mesh_indices()

In [69]:
bending_springs = 2

In [70]:
spring_offsets = []
if bending_springs == 1:
    for i in range(-1, 2):
        for j in range(-1, 2):
            for k in range(-1, 2):
                if (i, j, k) != (0, 0, 0):
                    spring_offsets.append(ti.Vector([i,j, k]))
elif bending_springs == 2:
    for i in range(-1, 2):
        for j in range(-1, 2):
            if (i, j) != (0, 0):
                spring_offsets.append(ti.Vector([i,j,0]))
elif bending_springs == 3:
    for i in range(-2, 3):
        for j in range(-2, 3):
            if (i, j) != (0, 0) and abs(i) + abs(j) <= 2:
                spring_offsets.append(ti.Vector([i, j]))

In [71]:
spring_offsets

[[-1 -1  0],
 [-1  0  0],
 [-1  1  0],
 [ 0 -1  0],
 [0 1 0],
 [ 1 -1  0],
 [1 0 0],
 [1 1 0]]

In [72]:
spring_Y = 3e4
spring_Y_z = 1e4

dashpot_damping = 1e4
dashpot_damping_z = 5e3 

drag_damping = 1.0  # 阻力

In [73]:
@ti.kernel
def substep():
    for i in ti.grouped(x):
        v[i] += gravity * dt

    for i in ti.grouped(x):
        force = ti.Vector([0.0, 0.0, 0.0])
        for spring_offset in ti.static(spring_offsets):
            j = i + spring_offset
            if 0 <= j[0] < n and 0 <= j[1] < n and 0 <= j[2] < layer:
                x_ij = x[i] - x[j]
                v_ij = v[i] - v[j]
                d = x_ij.normalized()
                current_dist = x_ij.norm()
                original_dist = quad_size * float(spring_offset.norm())
                force += -spring_Y * d * (current_dist / original_dist - 1)
                force += -v_ij.dot(d) * d * dashpot_damping * quad_size

        v[i] += force * dt

    for i in ti.grouped(x):
        v[i] *= ti.exp(-drag_damping * dt)
        offset_to_center = x[i] - ball_center[0]
        if offset_to_center.norm() <= ball_radius:
            normal = offset_to_center.normalized()
            v[i] -= min(v[i].dot(normal), 0) * normal
        x[i] += dt * v[i]

# @ti.kernel
# def substep():
#     for i, j, k in ti.ndrange(n, n, layer):
#         v[i, j, k] += gravity * dt 
# 
#     for i, j, k in ti.ndrange(n, n, layer):
#         force = ti.Vector([0.0, 0.0, 0.0])
# 
#         for spring_offset in ti.static(spring_offsets):
#             ni, nj, nk = i + spring_offset[0], j + spring_offset[1], k + spring_offset[2]
# 
#             # 确保索引在合法范围
#             if 0 <= ni < n and 0 <= nj < n and 0 <= nk < layer:
#                 x_ij = x[i, j, k] - x[ni, nj, nk]
#                 v_ij = v[i, j, k] - v[ni, nj, nk]
#                 current_dist = x_ij.norm()
#                 original_dist = quad_size * float(spring_offset.norm())
# 
#                 if original_dist > 0 and current_dist > 0:
#                     d = x_ij / current_dist 
#                     stiffness = spring_Y if spring_offset.z == 0 else spring_Y_z
#                     damping = dashpot_damping if spring_offset.z == 0 else dashpot_damping_z
# 
#                     force += -stiffness * d * (current_dist / original_dist - 1)
#                     force += -v_ij.dot(d) * d * damping * quad_size
# 
#         v[i, j, k] += force * dt
# 
#     for i, j, k in ti.ndrange(n, n, layer):
#         v[i, j, k] *= ti.exp(-drag_damping * dt) 
# 

#         offset_to_center = x[i, j, k] - ball_center[0]
#         if offset_to_center.norm() <= ball_radius:
#             normal = offset_to_center.normalized()
#             v[i, j, k] -= min(v[i, j, k].dot(normal), 0) * normal  # 反弹
# 
#         x[i, j, k] += v[i, j, k] * dt 

In [74]:
@ti.kernel
def update_vertices():
    for i, j, k in ti.ndrange(n, n, layer): 
        node_index = get_index(i,j,k)
        vertices[node_index] = x[i,j,k] 

In [75]:
current_n = 1

In [76]:
current_t = 0.0
initialize_mass_points()

In [ ]:
import time
start_time = time.time()

window = ti.ui.Window("Taichi Cloth Simulation on GGUI", (1024, 1024),
                      vsync=True)
canvas = window.get_canvas()
canvas.set_background_color((1, 1, 1))
scene = window.get_scene()
camera = ti.ui.Camera()

while window.running and current_n <= 5:
    if current_t > 1.5:
        # Reset
        initialize_mass_points()
        current_t = 0
        current_n += 1
        # print(current_n)

    for i in range(substeps):
        substep()
        current_t += dt
    update_vertices()
    
    camera.position(0.0, 0.0, 3)
    camera.lookat(0.0, 0.0, 0)
    scene.set_camera(camera)

    scene.point_light(pos=(0, 1, 2), color=(1, 1, 1))
    scene.ambient_light((0.5, 0.5, 0.5))
    scene.mesh(vertices,
               indices=indices,
               per_vertex_color=colors,
               two_sided=True)


    scene.particles(ball_center, radius=ball_radius * 0.95, color=(0.5, 0.42, 0.8))
    canvas.scene(scene)
    window.show()
    
    
end_time = time.time()
print("Elapsed time:", end_time - start_time)

# window.close()